version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WITH_NODE: "true"
        WITH_RUBY: "true" 
        WITH_PYTHON: "true"
        NODE_VERSION: "18.17.0"
        RUBY_VERSION: "3.2.0"
        PYTHON_VERSION: "3.11"
    volumes:
      - ../..:/workspaces:cached
      - rvm-cache:/home/vscode/.rvm
      - bundle-cache:/home/vscode/.bundle
    command: sleep infinity
    networks:
      - devnet

networks:
  devnet:

volumes:
  rvm-cache:
  bundle-cache:
