source 'https://rubygems.org'

# Testing framework
gem 'rspec', '~> 3.12'
gem 'minitest', '~> 5.18'

# Code quality
gem 'rubocop', '~> 1.50'
gem 'rubocop-rspec', '~> 2.20'

# Benchmarking
gem 'benchmark-ips', '~> 2.10'

# Development dependencies
group :development do
  gem 'pry', '~> 0.14'
  gem 'pry-byebug', '~> 3.10'
end
